### ISSUE TITLE
Maak bijv alle input tags 400px en stel dan eventueel uitzonderingen in

### ISSUE THREAD

**Issue by JeroenHeemskerk** [NickKoole/educom-webshop-basis-1696248352#15]
In je stylesheet.css **(die ik overigens in de /CSS folder had verwacht)** staat https://github.com/NickKoole/educom-webshop-basis-1696248352/blob/79b8c731ac2291dee8913e8aeedc2cecd1583d1d/stylesheet.css#L21-L23
hiermee maak je ALLEEN de inputs van het `type="text"` 400 pixels breed. maar wat nu als je `type="email"` of `type="tel"` gaat gebruiken, dan zijn deze niet 400 pixels breed.
 
Beter is het om de default voor alle inputs 400 pixels te laten zijn en dan misschien een paar types zoals submit en radio uitzonderen.
```CSS
 input, textarea { 
     width: 400px; 
 } 
 input[type=submit], input[type=radio] { 
     width: auto; 
 } 
```
